# Generated by Django 3.2.16 on 2024-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('superuser', 'Superuser'), ('moderator', 'Moderator')], default='user', max_length=20),
        ),
    ]
