# Generated by Django 3.2.16 on 2024-06-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userprofile_score'),
        ('login', '0005_alter_userprofile_club'),
    ]

    operations = [
    ]
