# Generated by Django 3.2.16 on 2024-06-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_merge_20240605_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='score',
        ),
    ]
