# Generated by Django 4.2.6 on 2023-11-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
