# Generated by Django 4.2.6 on 2023-11-06 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_content_post_contenu_rename_title_post_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_de_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
