# Generated by Django 4.2.6 on 2023-11-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
