# Generated by Django 3.2.16 on 2024-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20240220_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.TextField(blank=True, null=True, verbose_name='auth.User'),
        ),
    ]
