# Generated by Django 3.2.16 on 2024-04-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20240417_1811'),
        ('feed', '0015_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.info_clubs'),
        ),
    ]
