# Generated by Django 3.2.16 on 2024-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_post_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
