# Generated by Django 3.2.16 on 2024-06-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_alter_post_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenu',
            field=models.TextField(default=' '),
        ),
    ]
