# Generated by Django 4.2.6 on 2023-11-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classement", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Classement",
            new_name="Personne",
        ),
    ]
