# Generated by Django 4.2.6 on 2023-11-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classement", "0002_rename_classement_personne"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Personne",
            new_name="Utilisateur",
        ),
    ]
