# Generated by Django 3.2.16 on 2024-04-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Info_Clubs',
        ),
    ]
