# Generated by Django 3.2.16 on 2024-04-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0003_auto_20240417_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.info_clubs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.AddField(
            model_name='info_clubs',
            name='membres',
            field=models.ManyToManyField(related_name='clubs_subscribed', through='clubs.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
