# Generated by Django 3.2.16 on 2024-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20240417_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_clubs',
            name='secretaire',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='info_clubs',
            name='tresorier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='info_clubs',
            name='vp1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='info_clubs',
            name='vp2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
