# Generated by Django 3.2.16 on 2024-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20240417_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_clubs',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
