# Generated by Django 3.2.16 on 2024-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20240523_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_clubs',
            name='nom_affiche',
            field=models.CharField(default='', max_length=50),
        ),
    ]
