# Generated by Django 3.2.16 on 2024-06-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_info_clubs_score'),
        ('clubs', '0006_info_clubs_nom_affiche'),
    ]

    operations = [
    ]
